M48
; DRILL file {KiCad 7.0.6} date Fri Dec  8 17:53:41 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-12-08T17:53:41-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.300
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.000
%
G90
G05
T1
X140.35Y-145.39
T2
X172.57Y-73.025
X172.57Y-119.975
X197.08Y-73.025
X197.08Y-119.975
T0
M30
