M48
; DRILL file {KiCad 8.0.7} date 2025-07-01T23:11:29-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-07-01T23:11:29-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.7
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.300
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.000
%
G90
G05
T1
X140.35Y-145.39
T2
X172.57Y-73.025
X172.57Y-119.975
X197.08Y-73.025
X197.08Y-119.975
M30
